backend/controllers/AdminController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\AdminLoginForm;
use common\models\User;
use backend\models\UserDetailsFrontEnd;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\helpers\Url;


/**
 * Admin controller for main admin actions
 */
class AdminController extends Controller
{
    /**
     * Required variables
     */
    public $errors;
    public $path;
    public $filename;
    public $avatar;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['dashboard', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['getusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['viewusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['editusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['createuser', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['updateuser', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['changeuserstatus', 'error'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'dashboard' => ['post'],
                    'getusers' => ['post'],
                    'editusers' => ['post'],
                    'viewusers' => ['post'],
                    'createuser' => ['post'],
                    'updateuser' => ['post'],
                    'deleteuser' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
         return [
             'error' => [
                 'class' => 'yii\web\ErrorAction',
             ],
         ];
    }

    /*
    * Function to get back end dashboard and its values
    *  @return mixed
    */

    public function actionDashboard()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $model=new UserDetailsFrontEnd();
         Yii::$app->response->format = Response::FORMAT_JSON;
         $active_users = $model->getcount('active');
         $non_active_users = $model->getcount('inactive');
         $total_users = $model->getcount('total');
         $new_users = $model->getcount('new');
         return array('view' => $this->renderAjax('default',array('active_users' => $active_users,'non_active_users'=>$non_active_users,'total_users'=>$total_users,'new_users'=>$new_users),true));
    }

    /*
    * Function to get front end users list to display
    *  @return mixed
    */

    public function actionGetusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $model=new UserDetailsFrontEnd();
         Yii::$app->response->format = Response::FORMAT_JSON;
         $ul = $model->getuserlist();
         return array('view' => $this->renderAjax('users',array('user_list'=>$ul),true));
    }

    /*
    * Function to get front end user to edit
    *  @return mixed
    */

    public function actionEditusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $us=array();
         $model=new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
         Yii::$app->response->format = Response::FORMAT_JSON;
         if(Yii::$app->request->post('user_id') !=''){
            $us = $model->getuserdetails(Yii::$app->request->post('user_id'));
            $model->user_id=Yii::$app->request->post('user_id');
            $model->new = 'no';
            $model->update();
         }
         return array('view' => $this->renderAjax('userEditView',array('user'=>$us,'model'=>$model),true));
    }

    /*
    * Function to get front end user to view
    *  @return mixed
    */

    public function actionViewusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $us=array();
         $model=new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
         Yii::$app->response->format = Response::FORMAT_JSON;
         if(Yii::$app->request->post('user_id') !=''){
            $us = $model->getuserdetails(Yii::$app->request->post('user_id'));
            $model->user_id=Yii::$app->request->post('user_id');
            $model->new = 'no';
            $model->update();
         }
         return array('view' => $this->renderAjax('userOverView',array('user'=>$us),true));
    }

    /*
    * Function to validate each user input based on scenarios
    *  @param mixed 
    *  @return mixed
    */

    public function actionValidate($model){
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

    /*
    * Function to upload user avatar from admin
    *  @param mixed 
    *  @return bool
    */

    public function actionAvatar($model){
        if(Yii::$app->request->post()!=''){
            $image = UploadedFile::getInstance($model, 'image');
            if (isset($image)) {
                $model->filename = $image->name;
                $ext = end((explode(".", $image->name)));
                $model->avatar = Yii::$app->security->generateRandomString().".{$ext}";
                $path = Yii::getAlias('@frontend') . '/web/uploads/' . $model->avatar;
                if($image->saveAs($path)){
                    return true;
                }
            }            
            return false;
        }
    }

    /*
    * Function to create a front end user
    *  @return mixed
    */

    public function actionCreateuser() {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $model = new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_CREATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors);
        }
        $model->load(Yii::$app->request->post());
        $this->actionAvatar($model);
        if($model->create()){
            return array('result'=>'success','msg'=>'Successfully Created');
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to save');
    }

    /*
    * Function to update a front end user
    *  @return mixed
    */

    public function actionUpdateuser(){
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $old_file="";
        $model = new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors);
        }
        $model->load(Yii::$app->request->post());
        $model->user_id=Yii::$app->request->post('user_id');
        if($this->actionAvatar($model)){
            $user=User::findOne($model->user_id);
            if(isset($user->avatar)){
                $old_file=$user->avatar;
            }
        }
        if($model->update()){
            @unlink('../frontend/web/uploads/'.$old_file);
            return array('result'=>'success','msg'=>'Successfully Updated!');
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to update');
    }

    /*
    * Function to get change users status
    *  @return mixed
    */

    public function actionChangeuserstatus(){
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $model = new UserDetailsFrontEnd();
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model->user_id = Yii::$app->request->post('user_id');
        $model->action = Yii::$app->request->post('action');
        if($model->doaction()){
            return array('result'=>'success','msg'=>'Successfully deleted/changed!') ;
        }
        return array('result'=>'error','msg'=>'Unable to delete/change!');
    }
}

backend/views/admin/default.php
<div class="row">
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue">
                            <div class="panel-left pull-left brown">
                                <i class="fa fa-users fa-5x"></i>
                                
                            </div>
                            <div class="panel-right">
                            <h3><?=$new_users;?> </h3>
                             <strong>No. of New users</strong>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue">
                            <div class="panel-left pull-left blue">
                                <i class="fa fa-users fa-5x"></i>
                                
                            </div>
                            <div class="panel-right">
							<h3><?=$total_users;?> </h3>
                             <strong>No. of Total users</strong>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-left pull-left green">
                                <i class="fa fa-users fa-5x"></i>
                                
                            </div>
                            <div class="panel-right">
                            <h3><?=$active_users;?> </h3>
                             <strong>No. of Active users</strong>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-brown">
                            <div class="panel-left pull-left red">
                                <i class="fa fa-users fa-5x"></i>
                                
                            </div>
                            <div class="panel-right">
                            <h3><?=$non_active_users;?> </h3>
                             <strong>No. of Non-active users</strong>

                            </div>
                        </div>
                    </div>
                </div>

backend/views/admin/userEditView.php
<?php
	use yii\helpers\Html;
	use yii\widgets\ActiveForm;
    use yii\web\Application;
	use kartik\file\FileInput;
    use backend\assets\AppAsset;
	use borales\extensions\phoneInput\PhoneInput;

    AppAsset::register($this);
	echo "<center><h3>Create/Edit Users</h3></center>";
    $avatar=isset($user['avatar'])? $user['avatar'] : '';
    if($avatar !=''){
        echo "<div id='userphoto'><img src='../frontend/web/uploads/".$avatar."' width='170' alt='avatar'></div>";
    }
	echo "<br>";
	echo "<center><span id='res_msg'></span></center>";
	$ajax_action=isset($user['id']) ? Yii::$app->getUrlManager()->createUrl('admin/updateuser') : Yii::$app->getUrlManager()->createUrl('admin/createuser');
    $form = ActiveForm::begin([
    			'action'=>$ajax_action,
                'options' => [
                    'id' => 'update-user',
                    'enctype' => 'multipart/form-data',
                ],
    ]);
    $user['id']=isset($user['id'])? $user['id'] : '';
    $user['user_full_name']=isset($user['user_full_name'])? $user['user_full_name'] : '';
    $user['user_address']=isset($user['user_address'])? $user['user_address'] : '';
    $user['contact_no']=isset($user['contact_no'])? $user['contact_no'] : '';
    $user['email']=isset($user['email'])? $user['email'] : '';
    $user['status']=isset($user['status'])? $user['status'] : '';
    $user['user_age']=isset($user['user_age'])? $user['user_age'] : '';
    $user['user_gender']=isset($user['user_gender'])? $user['user_gender'] : '';
     echo Html::hiddenInput('user_id', $user['id']);
     echo $form->field($model, 'user_full_name')->textInput(array('value'=>$user['user_full_name']))->label('Name');
     if($user['id'] == ''){
     	$user['username']=isset($user['username'])? $user['username'] : '';
     	echo $form->field($model, 'username')->textInput(array('value'=>$user['username']))->label('Username');
     	echo $form->field($model, 'password')->passwordInput()->label('Password');
     	echo $form->field($model, 'repeatpassword')->passwordInput()->label('Repeat Password');
     	echo $form->field($model, 'email')->textInput(array('value'=>$user['email']))->label('Email');
     }
     echo $form->field($model, 'user_age')->textInput(array('value'=>$user['user_age']))->label('Age');
     echo $form->field($model, 'user_gender')->dropDownList(['male' => 'Male', 'female' => 'Female'],
            ['options' =>
                    [                        
                       $user['user_gender'] => ['Selected' => 'selected']
                    ]
          ]);
     echo $form->field($model, 'user_address')->textarea(array('value'=>$user['user_address']))->label('Address');
     echo $form->field($model, 'status')->dropDownList(['10' => 'Active', '20' => 'Inactive'],
     		['options' =>
                    [                        
                       $user['status'] => ['Selected' => 'selected']
                    ]
          ]);
     if($user['contact_no'] != ''){
        $user['contact_no']= '+'.$user['contact_no'];
     }   
     echo $form->field($model, 'contact_no')->widget(PhoneInput::classname(), [
                'name' => 'contact_no',
     			'jsOptions' => [
         			'allowExtensions' => true,
         			'nationalMode'=>false,
                    ],
                'options'=>[
                'value'=>$user['contact_no']
                ]    
            ])->label('Contact No');
     echo $form->field($model, 'image')->widget(FileInput::classname(), [
     			'name' => 'filename',
                'options'=>['accept'=>'image/*'],
                'pluginOptions'=>['allowedFileExtensions'=>['jpg','gif','png'],
                'maxFileSize' => '2048',
                'showUpload' => false],
            ]);
     echo '<center>'
     .Html::button('Cancel', ['class'=> 'btn btn-default','data-dismiss'=>'modal']).'&nbsp;&nbsp;'
     .Html::submitButton('Submit', ['class'=> 'btn btn-primary','id'=>'submit-user']).'</center>' ;        
    ActiveForm::end();
    

    ?>

backend/views/admin/userOverView.php
<?php
    use yii\helpers\Html;
	echo "<center><h3>User Overview</h3></center>";
    $avatar=isset($user['avatar'])? $user['avatar'] : '';
    if($avatar !=''){
        echo "<div id='userphoto'><img src='../frontend/web/uploads/".$avatar."' width='170' alt='avatar'></div>";
    }
	echo "<br>";
    $user_full_name=isset($user['user_full_name'])? $user['user_full_name'] : '';
    $username=isset($user['username'])? $user['username'] : '';
    $user_address=isset($user['user_address'])? $user['user_address'] : '';
    $contact_no=isset($user['contact_no'])? '+'.$user['contact_no'] : '';
    $email=isset($user['email'])? $user['email'] : '';
    $status=isset($user['status'])? $user['status'] : '';
?>
    <p class="setting"><span>Name </span> <?php echo $user_full_name;?>&nbsp;</p>
    <p class="setting"><span>Username </span> <?php echo $username;?>&nbsp;</p>
    <p class="setting"><span>Email </span> <?php echo $email;?>&nbsp;</p>
    <p class="setting"><span>Contact No </span> <?php echo $contact_no;?>&nbsp;</p>
    <p class="setting"><span>Address </span> <?php echo $user_address;?>&nbsp;</p>
    <p class="setting"><span>Status </span> <?php if($status=='10'){echo "Active";}else{echo "Not Active";}?>&nbsp;</p>
<?php
    echo '<center>'.Html::button('Cancel', ['class'=> 'btn btn-default','data-dismiss'=>'modal']).'&nbsp;&nbsp;</center>' ; 
?>

backend/views/admin/users.php
<div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             Users list
                             <div style="position:relative;">
                                <button class="btn btn-success refresh_table"> Refresh</button>
                             </div>
                             <div style="position:relative;margin-left:84%;">
                                <button class="btn btn-success edit_user"  data-id=""><i class="fa fa-edit "></i> Create new user</button>
                             </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>SI.No</th>
                                            <th>Name</th>
                                            <th>Username</th>
                                            <th>Email</th>
                                            <th>Activation</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                   <?php $count=1;
                                   foreach ($user_list as $user) {
                                        $new="";
                                        if($user['new']=='1'){
                                            $new="success";
                                        }
                                    ?>     
                                        <tr class="<?php $class=$count%2 ? 'odd' : 'even'; echo $class;?>  gradeX <?php echo $new;?>" id="row_id_<?=$user['id'];?>">
                                            <td><?=$count;?></td>
                                            <td><?=$user['user_full_name'];?></td>
                                            <td><?=$user['username'];?></td>
                                            <td><?=$user['email'];?></td>
                                            <td class="center">
                                                <?php if($user['status'] ==10){ ?>
                                                    <a href="javascript:void(0);" title="Turn off activation" class="btn btn-success btn-sm btn-status" id="action_<?=$user['id'];?>" data-status="deactivate" data-id="<?=$user['id'];?>">On</a></td>
                                                <?php }else{
                                                ?>
                                                    <a href="javascript:void(0);" title="Turn on activation" class="btn btn-danger btn-sm btn-status" id="action_<?=$user['id'];?>" data-status="activate" data-id="<?=$user['id'];?>">Off</a></td>
                                                <?php }?>
                                                
                                            <td class="center">
                                                <button class="btn btn-default view_user" title="View this user profile" data-id="<?=$user['id'];?>"><i class="fa fa-pencil"></i> View</button>
                                                <button class="btn btn-primary edit_user" title="Edit this user profile" data-id="<?=$user['id'];?>"><i class="fa fa-edit "></i> Edit</button>
                                                <button class="btn btn-danger del_user" title="Delete this user profile" data-id="<?=$user['id'];?>"><i class="fa fa-pencil"></i> Delete</button>
                                            </td>
                                        </tr>
                                   <?php  ++$count;} ?>    
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>

                

                <script>
                        $(document).ready(function () {
                            $('#dataTables-example').dataTable();
                        });
                </script>