backend/controllers/AdminController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\AdminLoginForm;
use common\models\User;
use backend\models\UserDetailsFrontEnd;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\helpers\Url;


/**
 * Admin controller for main admin actions
 */
class AdminController extends Controller
{
    /**
     * Required variables
     */
    public $errors;
    public $path;
    public $filename;
    public $avatar;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['dashboard', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['getusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['viewusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['editusers', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['createuser', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['updateuser', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['changeuserstatus', 'error'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'dashboard' => ['post'],
                    'getusers' => ['post'],
                    'editusers' => ['post'],
                    'viewusers' => ['post'],
                    'createuser' => ['post'],
                    'updateuser' => ['post'],
                    'deleteuser' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
         return [
             'error' => [
                 'class' => 'yii\web\ErrorAction',
             ],
         ];
    }

    /*
    * Function to get back end dashboard and its values
    *  @return mixed
    */

    public function actionDashboard()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $model=new UserDetailsFrontEnd();
         Yii::$app->response->format = Response::FORMAT_JSON;
         $active_users = $model->getcount('active');
         $non_active_users = $model->getcount('inactive');
         $total_users = $model->getcount('total');
         $new_users = $model->getcount('new');
         return array('view' => $this->renderAjax('default',array('active_users' => $active_users,'non_active_users'=>$non_active_users,'total_users'=>$total_users,'new_users'=>$new_users),true));
    }

    /*
    * Function to get front end users list to display
    *  @return mixed
    */

    public function actionGetusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $model=new UserDetailsFrontEnd();
         Yii::$app->response->format = Response::FORMAT_JSON;
         $ul = $model->getuserlist();
         return array('view' => $this->renderAjax('users',array('user_list'=>$ul),true));
    }

    /*
    * Function to get front end user to edit
    *  @return mixed
    */

    public function actionEditusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $us=array();
         $model=new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
         Yii::$app->response->format = Response::FORMAT_JSON;
         if(Yii::$app->request->post('user_id') !=''){
            $us = $model->getuserdetails(Yii::$app->request->post('user_id'));
            $model->user_id=Yii::$app->request->post('user_id');
            $model->new = 'no';
            $model->update();
         }
         return array('view' => $this->renderAjax('userEditView',array('user'=>$us,'model'=>$model),true));
    }

    /*
    * Function to get front end user to view
    *  @return mixed
    */

    public function actionViewusers()
    {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
         $us=array();
         $model=new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
         Yii::$app->response->format = Response::FORMAT_JSON;
         if(Yii::$app->request->post('user_id') !=''){
            $us = $model->getuserdetails(Yii::$app->request->post('user_id'));
            $model->user_id=Yii::$app->request->post('user_id');
            $model->new = 'no';
            $model->update();
         }
         return array('view' => $this->renderAjax('userOverView',array('user'=>$us),true));
    }

    /*
    * Function to validate each user input based on scenarios
    *  @param mixed 
    *  @return mixed
    */

    public function actionValidate($model){
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

    /*
    * Function to upload user avatar from admin
    *  @param mixed 
    *  @return bool
    */

    public function actionAvatar($model){
        if(Yii::$app->request->post()!=''){
            $image = UploadedFile::getInstance($model, 'image');
            if (isset($image)) {
                $model->filename = $image->name;
                $ext = end((explode(".", $image->name)));
                $model->avatar = Yii::$app->security->generateRandomString().".{$ext}";
                $path = Yii::getAlias('@frontend') . '/web/uploads/' . $model->avatar;
                if($image->saveAs($path)){
                    return true;
                }
            }            
            return false;
        }
    }

    /*
    * Function to create a front end user
    *  @return mixed
    */

    public function actionCreateuser() {
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $model = new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_CREATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors);
        }
        $model->load(Yii::$app->request->post());
        $this->actionAvatar($model);
        if($model->create()){
            return array('result'=>'success','msg'=>'Successfully Created');
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to save');
    }

    /*
    * Function to update a front end user
    *  @return mixed
    */

    public function actionUpdateuser(){
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $old_file="";
        $model = new UserDetailsFrontEnd(['scenario' => UserDetailsFrontEnd::SCENARIO_UPDATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors);
        }
        $model->load(Yii::$app->request->post());
        $model->user_id=Yii::$app->request->post('user_id');
        if($this->actionAvatar($model)){
            $user=User::findOne($model->user_id);
            if(isset($user->avatar)){
                $old_file=$user->avatar;
            }
        }
        if($model->update()){
            @unlink('../frontend/web/uploads/'.$old_file);
            return array('result'=>'success','msg'=>'Successfully Updated!');
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to update');
    }

    /*
    * Function to get change users status
    *  @return mixed
    */

    public function actionChangeuserstatus(){
        if (\Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
            return $this->redirect(['site/login']);
        }
        $model = new UserDetailsFrontEnd();
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model->user_id = Yii::$app->request->post('user_id');
        $model->action = Yii::$app->request->post('action');
        if($model->doaction()){
            return array('result'=>'success','msg'=>'Successfully deleted/changed!') ;
        }
        return array('result'=>'error','msg'=>'Unable to delete/change!');
    }
}

backend/views/layouts/common.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
$this->title = 'CRUD-FAT-BACKEND';
$this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <style type="text/css">
        body {
            background: none !important;
        }
    </style>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'CRUD-FAT-ADMIN',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; FAT-CRUD <?= date('Y') ?></p>

        <p class="pull-right">FAT-POWERED</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use nirvana\showloading\ShowLoadingAsset;

ShowLoadingAsset::register($this);
AppAsset::register($this);
 $this->title = 'CRUD-FAT-BACKEND'; 
 $this->beginPage()?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <script type="text/javascript">
        var default_url="<?php echo \Yii::$app->getUrlManager()->createUrl('admin/dashboard') ?>";
        var user_view_url="<?php echo \Yii::$app->getUrlManager()->createUrl('admin/getusers') ?>";
        var user_overview_url="<?php echo \Yii::$app->getUrlManager()->createUrl('admin/viewusers') ?>";
        var user_edit_url="<?php echo \Yii::$app->getUrlManager()->createUrl('admin/editusers') ?>";
        var user_action_url="<?php echo \Yii::$app->getUrlManager()->createUrl('admin/changeuserstatus') ?>";
    </script>
    <?php $this->head() ?>
</head>

<body>
<?php $this->beginBody() ?>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:void(0);"><i class="fa fa-gear"></i> <strong>CRUD-FAT-ADMIN</strong></a>
            </div>  
             <ul class="nav navbar-top-links navbar-right"> 
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                         <li>
                            <?php
                               echo Html::beginForm(['/site/logout'], 'post')
                              . Html::submitButton(
                                'Logout',
                                ['class' => 'fa fa-sign-out fa-fw']
                            )
                            . Html::endForm();
                            ?>    
                        </li> 
                       
                           
                    </ul>
                     
                </li>
                <!-- /.dropdown -->
            </ul> 
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
		<div id="sideNav" href=""><i class="fa fa-caret-right"></i></div>
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a class="active-menu l-menu" href="javascript:void(0);" id="show_dash"><i class="fa fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a class="l-menu" href="javascript:void(0);" id="show_user"><i class="fa fa-user"></i> Users</a>
                    </li>
					


                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                             <small>Dashboard</small>
                        </h1>
						<ol class="breadcrumb">
                          <li><a href="javascript:void(0);">Admin</a></li>
                          <li class="active"><a href="javascript:void(0);">Dashboard</a></li>
                        </ol>
                    </div>
                </div>
				
				
                <!-- /. ROW  -->
            <div id="temp_view">
                
            </div>
		
				<footer>
				
        
				</footer>
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <style type="text/css">
    .modal-lg{
        width:500px !important;
    }
    </style>
    <?php
                    yii\bootstrap\Modal::begin([
                        'headerOptions' => ['id' => 'modalHeader'],
                        'id' => 'modal',
                        'size' => 'modal-lg',
                        'clientOptions' => ['backdrop' => 'static', 'keyboard' => TRUE]
                    ]);
                    echo "<div id='modalContent'><div style='text-align:center'><img src='web/img/loader.gif'></div></div>";
                    yii\bootstrap\Modal::end();
                ?>
<?php $this->endBody() ?>

</body>

</html>
<?php $this->endPage() ?>