frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;
use common\models\User;
use frontend\models\UserProfile;

/**
 * User controller
 */
class UserController extends Controller
{
	public $errors;
	/**
     * Setting behaviours
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['userupdate', 'profile','updateuserpassword','delete'],
                'rules' => [
                    [
                        'actions' => ['userupdate', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['profile' ,'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['updateuserpassword' ,'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['delete' ,'error'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'profile' => ['get'],
                    'userupdate' => ['post'],
                    'updateuserpassword' => ['post'],
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
         return [
             'error' => [
                 'class' => 'yii\web\ErrorAction',
             ],
         ];
    }

	/**
     * Displays user profile page.
     *
     * @return mixed
     */
    public function actionProfile()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile();
        return $this->render('profile',['model'=>$model]);
    }


    /**
     * Updates user avatar
     *
     * @return mixed
     */
    public function actionUseravatar()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_AVATAR]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        if ($model->load(Yii::$app->request->post())) {
            $image = UploadedFile::getInstance($model, 'image');
            if(!$image){
                return array('result'=>'error','type'=>'other','msg'=>'Please select an image to upload!','img'=>'','details'=>array());
            }
            $model->filename = $image->name;
            $ext = end((explode(".", $image->name)));
            $model->avatar = Yii::$app->security->generateRandomString().".{$ext}";
            $path = Yii::$app->basePath . '/web/uploads/' . $model->avatar;
            if(isset(Yii::$app->user->identity->avatar)){
                $old_file=Yii::$app->user->identity->avatar;
            }
            if($model->update()){
                if($image->saveAs($path)){
                    unlink('../frontend/web/uploads/'.$old_file);
                    return array('result'=>'success','msg'=>'Successfully uploaded!','img'=>$model->avatar,'details'=>array());
                }
            } else {
                return array('result'=>'error','type'=>'other','msg'=>'Unable to upload','img'=>'','details'=>array());
            }
        }
    }

    /**
     * Updates user password
     *
     * @return mixed
     */

    public function actionUpdateuserpassword(){
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_CHANGE_PWD]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors,'img'=>'','details'=>array());
        }
        $model->load(Yii::$app->request->post());
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully changed password!','img'=>'','details'=>array());
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to change password','img'=>'','details'=>array());
    }

    /**
     * Perform validation action.
     * @param mixed
     * @return mixed
     */

    public function actionValidate($model){
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

    /**
     * Updates user profile
     *
     * @return mixed
     */
    public function actionUserupdate()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_UPDATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors,'img'=>'','details'=>array());
        }
        $model->load(Yii::$app->request->post());
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully Updated!','img'=>'','details'=>array('user_full_name'=>$model->user_full_name,'user_address'=>$model->user_address,'user_age'=>$model->user_age,'contact_no'=>$model->contact_no));
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to update','img'=>'','details'=>array());
        
    }

    /**
     * To Cancel user account
     *
     * @return mixed
     */
    public function actionDelete(){
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_DELETE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model->status=User::STATUS_DELETED;
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully cancelled! We look forward to serve you again. Thank you!') ;
        }
        return array('result'=>'error','msg'=>'Unable to cancel!. An error occured.');
    }
}	

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
$this->title = 'CRUD-FAT-FRONTEND';
$this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <script type="text/javascript">
        var user_del_url="<?php echo \Yii::$app->getUrlManager()->createUrl('user/delete') ?>";
        var user_logout_url="<?php echo \Yii::$app->getUrlManager()->createUrl('site/logout') ?>";
    </script>    
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'CRUD-FAT-USER',
        'brandUrl' => 'javascript:void(0)',
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems = [
         ['label' => 'Profile', 'url' => ['/user/profile']],
    ];
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; FAT-CRUD <?= date('Y') ?></p>

        <p class="pull-right">FAT-POWERED</p>
    </div>
</footer>

<?php $this->endBody() ?>
<script type="text/javascript">
  $(function(){
    $('#profiletabs ul li a').on('click', function(e){
      e.preventDefault();
      var newcontent = $(this).attr('href');
      
      $('#profiletabs ul li a').removeClass('sel');
      $(this).addClass('sel');
      
      $('#content section').each(function(){
        if(!$(this).hasClass('hidden')) { $(this).addClass('hidden'); }
      });
      
      $(newcontent).removeClass('hidden');
    });
  });
</script>
</body>
</html>
<?php $this->endPage() ?>