common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    const STATUS_INACTIVE = 20;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED,self::STATUS_INACTIVE]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;
use common\models\User;
use frontend\models\UserProfile;

/**
 * User controller
 */
class UserController extends Controller
{
	public $errors;
	/**
     * Setting behaviours
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['userupdate', 'profile','updateuserpassword','delete'],
                'rules' => [
                    [
                        'actions' => ['userupdate', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['profile' ,'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['updateuserpassword' ,'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['delete' ,'error'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'profile' => ['get'],
                    'userupdate' => ['post'],
                    'updateuserpassword' => ['post'],
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
         return [
             'error' => [
                 'class' => 'yii\web\ErrorAction',
             ],
         ];
    }

	/**
     * Displays user profile page.
     *
     * @return mixed
     */
    public function actionProfile()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile();
        return $this->render('profile',['model'=>$model]);
    }


    /**
     * Updates user avatar
     *
     * @return mixed
     */
    public function actionUseravatar()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_AVATAR]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        if ($model->load(Yii::$app->request->post())) {
            $image = UploadedFile::getInstance($model, 'image');
            if(!$image){
                return array('result'=>'error','type'=>'other','msg'=>'Please select an image to upload!','img'=>'','details'=>array());
            }
            $model->filename = $image->name;
            $ext = end((explode(".", $image->name)));
            $model->avatar = Yii::$app->security->generateRandomString().".{$ext}";
            $path = Yii::$app->basePath . '/web/uploads/' . $model->avatar;
            if(isset(Yii::$app->user->identity->avatar)){
                $old_file=Yii::$app->user->identity->avatar;
            }
            if($model->update()){
                if($image->saveAs($path)){
                    unlink('../frontend/web/uploads/'.$old_file);
                    return array('result'=>'success','msg'=>'Successfully uploaded!','img'=>$model->avatar,'details'=>array());
                }
            } else {
                return array('result'=>'error','type'=>'other','msg'=>'Unable to upload','img'=>'','details'=>array());
            }
        }
    }

    /**
     * Updates user password
     *
     * @return mixed
     */

    public function actionUpdateuserpassword(){
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_CHANGE_PWD]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors,'img'=>'','details'=>array());
        }
        $model->load(Yii::$app->request->post());
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully changed password!','img'=>'','details'=>array());
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to change password','img'=>'','details'=>array());
    }

    /**
     * Perform validation action.
     * @param mixed
     * @return mixed
     */

    public function actionValidate($model){
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

    /**
     * Updates user profile
     *
     * @return mixed
     */
    public function actionUserupdate()
    {
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_UPDATE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $this->errors=$this->actionValidate($model);
        if(!empty($this->errors)){
            return array('result'=>'error','type'=>'validation','msg'=>$this->errors,'img'=>'','details'=>array());
        }
        $model->load(Yii::$app->request->post());
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully Updated!','img'=>'','details'=>array('user_full_name'=>$model->user_full_name,'user_address'=>$model->user_address,'user_age'=>$model->user_age,'contact_no'=>$model->contact_no));
        }
        return array('result'=>'error','type'=>'other','msg'=>'Unable to update','img'=>'','details'=>array());
        
    }

    /**
     * To Cancel user account
     *
     * @return mixed
     */
    public function actionDelete(){
        if (\Yii::$app->user->isGuest) {
             return $this->redirect(['site/login']);
        }
        $model = new UserProfile(['scenario' => UserProfile::SCENARIO_USER_DELETE]);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model->status=User::STATUS_DELETED;
        if($model->update()){
            return array('result'=>'success','msg'=>'Successfully cancelled! We look forward to serve you again. Thank you!') ;
        }
        return array('result'=>'error','msg'=>'Unable to cancel!. An error occured.');
    }
}	

frontend/views/user/profile.php
<?php
use yii\helpers\Html;
use common\models\UserDetails;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

$user_full_name= !empty(Yii::$app->user->identity->user_full_name) ?  Yii::$app->user->identity->user_full_name : " ";
$username= !empty(Yii::$app->user->identity->username) ?  Yii::$app->user->identity->username : " ";
$email= !empty(Yii::$app->user->identity->email) ?  Yii::$app->user->identity->email : " ";
$contact_no= !empty(Yii::$app->user->identity->contact_no) ?  "+".Yii::$app->user->identity->contact_no : "";
$user_address= !empty(Yii::$app->user->identity->user_address) ?  Yii::$app->user->identity->user_address : " ";
$user_age= !empty(Yii::$app->user->identity->user_age) ?  Yii::$app->user->identity->user_age : " ";
$user_gender= !empty(Yii::$app->user->identity->user_gender) ?  Yii::$app->user->identity->user_gender : " ";
$avatar = !empty(Yii::$app->user->identity->avatar) ?  "../web/uploads/".Yii::$app->user->identity->avatar : "../web/images/avatar.png";
 
?>
<div id="w">
    <div id="content" class="clearfix">
      <div id="userphoto"><img src="<?php echo $avatar;?>" width="170" alt="default avatar" id="user_img"></div>
      <h1><span id="user_name"><?php $name=empty(Yii::$app->user->identity->user_full_name) ? $username : $user_full_name; echo $name;?></span></h1>

      <nav id="profiletabs">
        <ul class="clearfix">
          <li><a href="#profile" class="sel">Overview</a></li>
          <li><a href="#edit_profile" class="">Edit Profile</a></li>
          <li><a href="#avatar" class="">Avatar</a></li>
          <li><a href="#settings" class="">Settings</a></li>
        </ul>
      </nav>
      
      <section id="profile" class="">
        <p>Edit user settings:</p>
        
        <p class="setting"><span>Name </span> <span id="user_full_name_view"><?php echo $user_full_name;?></span>&nbsp;</p>

        <p class="setting"><span>Username </span> <span><?php echo $username;?></span>&nbsp;</p>

        <p class="setting"><span>Age </span> <span id="user_age_view"><?php echo $user_age;?></span>&nbsp;</p>

        <p class="setting"><span>Gender </span> <span><?php echo $user_gender;?></span>&nbsp;</p>
        
        <p class="setting"><span>Email </span> <span><?php echo $email;?></span>&nbsp;</p>
        
        <p class="setting"><span>Contact No </span> <span id="contact_no_view"><?php echo $contact_no;?></span>&nbsp;</p>
        
        <p class="setting"><span>Address </span> <span id="user_address_view"><?php echo $user_address;?></span>&nbsp;</p>
        
      </section>
      
      <section id="edit_profile" class="hidden">
      <?php
      use borales\extensions\phoneInput\PhoneInput;
      echo "<h3>Create/Edit Users</h3>";
      echo "<br>";
      echo "<center><span id='res_msg_update-profile'></span></center>";
      $ajax_action= Yii::$app->getUrlManager()->createUrl('user/userupdate');
        $form = ActiveForm::begin([
              'action'=>$ajax_action,
                    'options' => [
                        'id' => 'update-profile',
                        'enctype' => 'multipart/form-data',
                    ],
        ]);
         echo $form->field($model, 'user_full_name')->textInput(array('value'=>$user_full_name))->label('Name');
         
         echo $form->field($model, 'user_address')->textarea(array('value'=>$user_address))->label('Address');
         echo $form->field($model, 'user_age')->textInput(array('value'=>$user_age))->label('Age');
         echo $form->field($model, 'user_gender')->dropDownList(['male' => 'Male', 'female' => 'Female'],
                ['options' =>
                        [                        
                           $user_gender => ['Selected' => 'selected']
                        ]
              ]);
         echo $form->field($model, 'contact_no')->widget(PhoneInput::classname(), [
                    'name' => 'contact_no',
                    'jsOptions' => [
                        'allowExtensions' => true,
                        'nationalMode'=>false],
                    'options'=>[
                        'value'=>$contact_no
                    ]    

                ])->label('Contact No');

         echo '<center>'
         .Html::resetButton('Reset', ['class'=> 'btn btn-default']).'&nbsp;&nbsp;'
         .Html::submitButton('Submit', ['class'=> 'btn btn-primary update-user','data-form'=>'update-profile']).'</center>' ;        
        ActiveForm::end();
    ?>
      </section>
      <section id="avatar" class="hidden">
        <?php 
          echo "<h3>Upload Avatar</h3>";
          echo "<br>";
          echo "<center><span id='res_msg_update-avatar'></span></center>";
          $form = ActiveForm::begin([
                'options'=>['enctype'=>'multipart/form-data',
                'id' => 'update-avatar'], 
                'action'=>Yii::$app->getUrlManager()->createUrl('user/useravatar')
            ]);
            echo $form->field($model, 'image')->widget(FileInput::classname(), [
                'options'=>['accept'=>'image/*'],
                'pluginOptions'=>['allowedFileExtensions'=>['jpg','gif','png'],
                'maxFileSize' => '2048',
                'showUpload' => false]
            ]);
            echo Html::submitButton( 'Upload', [
                'class'=>'btn btn-success update-user','data-form'=>'update-avatar']
            );
            ActiveForm::end();
                    ?>
      </section>
      <section id="settings" class="hidden">
      <?php echo "<h3>Account cancellation/Change password</h3>";
      echo Html::button( 'Cancel my account', [
                'class'=>'btn btn-danger', 'id'=>'delete-button']
            );
      echo "<center><span id='res_msg_update-password'></span></center>";
        $form = ActiveForm::begin([
              'action'=>Yii::$app->getUrlManager()->createUrl('user/updateuserpassword'),
                    'options' => [
                        'id' => 'update-password',
                        'enctype' => 'multipart/form-data',
                    ],
        ]);
         echo $form->field($model, 'currentpassword')->passwordInput()->label('Current Password');
         echo $form->field($model, 'password')->passwordInput()->label('New Password');
         echo $form->field($model, 'repeatpassword')->passwordInput()->label('Confirm Password');
         

         echo '<center>'
         .Html::resetButton('Reset', ['class'=> 'btn btn-default']).'&nbsp;&nbsp;'
         .Html::submitButton('Submit', ['class'=> 'btn btn-primary update-user','data-form'=>'update-password']).'</center>' ;        
        ActiveForm::end();
    ?>
      </section>
    </div><!-- @end #content -->
    <style type="text/css">
    .modal-lg{
        width:500px !important;
    }
    </style>
    <?php
        yii\bootstrap\Modal::begin([
            'headerOptions' => ['id' => 'modalHeader'],
            'id' => 'modal',
            'size' => 'modal-lg',
            'clientOptions' => ['backdrop' => 'static', 'keyboard' => TRUE,'closeButton'=>FALSE]
        ]);
        echo "<div id='modalContent'><div style='text-align:center'><img src='../web/images/loader.gif'></div></div>";
        yii\bootstrap\Modal::end();
    ?>
  </div>